//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarketApp.StockDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.stockdataexpert.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.stockdataexpert.com/", ConfigurationName="StockDataService.StockDataSoap")]
    public interface StockDataSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stockdataexpert.com/StockPrice", ReplyAction="*")]
        StockMarketApp.StockDataService.StockPriceResponse StockPrice(StockMarketApp.StockDataService.StockPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.stockdataexpert.com/StockPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<StockMarketApp.StockDataService.StockPriceResponse> StockPriceAsync(StockMarketApp.StockDataService.StockPriceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockPrice", Namespace="http://www.stockdataexpert.com/", Order=0)]
        public StockMarketApp.StockDataService.StockPriceRequestBody Body;
        
        public StockPriceRequest() {
        }
        
        public StockPriceRequest(StockMarketApp.StockDataService.StockPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stockdataexpert.com/")]
    public partial class StockPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pubicKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public StockMarketApp.StockDataService.ArrayOfString stockCodes;
        
        public StockPriceRequestBody() {
        }
        
        public StockPriceRequestBody(string pubicKey, string hash, StockMarketApp.StockDataService.ArrayOfString stockCodes) {
            this.pubicKey = pubicKey;
            this.hash = hash;
            this.stockCodes = stockCodes;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StockPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StockPriceResponse", Namespace="http://www.stockdataexpert.com/", Order=0)]
        public StockMarketApp.StockDataService.StockPriceResponseBody Body;
        
        public StockPriceResponse() {
        }
        
        public StockPriceResponse(StockMarketApp.StockDataService.StockPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.stockdataexpert.com/")]
    public partial class StockPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StockPriceResult;
        
        public StockPriceResponseBody() {
        }
        
        public StockPriceResponseBody(string StockPriceResult) {
            this.StockPriceResult = StockPriceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StockDataSoapChannel : StockMarketApp.StockDataService.StockDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StockDataSoapClient : System.ServiceModel.ClientBase<StockMarketApp.StockDataService.StockDataSoap>, StockMarketApp.StockDataService.StockDataSoap {
        
        public StockDataSoapClient() {
        }
        
        public StockDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StockDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StockDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StockMarketApp.StockDataService.StockPriceResponse StockPrice(StockMarketApp.StockDataService.StockPriceRequest request) {
            return base.Channel.StockPrice(request);
        }
        
        public System.Threading.Tasks.Task<StockMarketApp.StockDataService.StockPriceResponse> StockPriceAsync(StockMarketApp.StockDataService.StockPriceRequest request) {
            return base.Channel.StockPriceAsync(request);
        }
    }
}
